version: ~> 1.0
sudo: false
language: node_js
node_js:
  - '10'
  - '12'
  - '13'
  - '14'
matrix:
  fast_finish: true
  allow_failures: []
cache: npm
install:
  - >-
    eval "$(curl -fsSL
    https://raw.githubusercontent.com/bevry/awesome-travis/master/scripts/node-install.bash)"
before_script:
  - >-
    eval "$(curl -fsSL
    https://raw.githubusercontent.com/bevry/awesome-travis/master/scripts/node-verify.bash)"
after_success:
  - >-
    eval "$(curl -fsSL
    https://raw.githubusercontent.com/bevry/awesome-travis/master/scripts/surge.bash)"
  - >-
    eval "$(curl -fsSL
    https://raw.githubusercontent.com/bevry/awesome-travis/master/scripts/node-publish.bash)"
notifications:
  email:
    recipients: >-
      RwnHbnv+h3l5RUaOJwzlDAzBkE6vniMp/INSS/xo1VDGlJgqwt6t5udfBk6rG+gjvRfnSnmWW+0lmP7EErOiJdT6cUaN+aof0HO2N1CpNwhnjslUh8ytVGszjbFU92LdDGOmspN9k5OQHAXGttCf7KmwFheTuJuhnu1qpox0MKtiXEP40zZzc4QEfsTFlJ3EtxLW0eTvN6xhLc9pfYqSC5ccR5p5APuC6Ss3VL0ymkfnXp93csj92Qod9zCNgfEILvydbKD7oqJQGxylKySRR9wonBxE+y/OeKtn83b8jM4uMHPJpqvKMn16VDtieSvQ4aL/riW1z0P5GrJIMvEijq0dyOuajwhFmM+q2tw2f3DBqQVmUxKYoZ0ZKGEF2Iq8fh64MRfbvozi0tZxd589RZIO8Q2p3qMacBhIYHU6hD1JUe1rk69vfdQDpXikMKk68sWld9Lnnq9LDS7/5WA7mgFtCg2cFMFf/hqagLV8C8+0+f+VIN2lia7Wd81wvXEW3K0agjQ31+rcTv3Hh3JxS6qyV/KNXxlR+mMy6O1rpIdblGBQ3JZmOBuwaAHVGk+k4EiZZB1L/ZuDilWujMnIEzLQ07hOVLMUChl4wW2s+h5GP8LMDpc6oij+59SoPXKgFwNkHiUQXkFlC7HvVYaO4eKNmzjxGncWP0BBeHgsQfI=
