version: ~> 1.0
sudo: false
language: node_js
node_js:
  - '10'
  - '12'
  - '13'
  - '14'
matrix:
  fast_finish: true
  allow_failures: []
cache: npm
install:
  - >-
    eval "$(curl -fsSL
    https://raw.githubusercontent.com/bevry/awesome-travis/9fa2fa025c77b463d03154f39922af95cadc9c67/scripts/node-install.bash)"
before_script:
  - >-
    eval "$(curl -fsSL
    https://raw.githubusercontent.com/bevry/awesome-travis/9fa2fa025c77b463d03154f39922af95cadc9c67/scripts/node-verify.bash)"
after_success:
  - >-
    eval "$(curl -fsSL
    https://raw.githubusercontent.com/bevry/awesome-travis/9fa2fa025c77b463d03154f39922af95cadc9c67/scripts/surge.bash)"
  - >-
    eval "$(curl -fsSL
    https://raw.githubusercontent.com/bevry/awesome-travis/9fa2fa025c77b463d03154f39922af95cadc9c67/scripts/node-publish.bash)"
notifications:
  email:
    recipients: >-
      JbsdpOnpD7oej3j0bGUG0D9uKU9C4IkciCXrwTGlaaBnBuJVVQ7lxahT0uGJuLX76RHeVQJo2SQ34Iqwsl2g3/ZaGqT6qAKqBHWWhKm7F4j8Mirx8Zw4612T2hV5SggNYFqYHItMb60P49AiElcH3TSYw3XVaw6TKvR1DEr8m1P7h/wwyD7eLe7otpeKwJdUK7e/cd71DqiwARJtf9JTUubBfGq57eEasD9yTiwZz0GtgTH+FOiC2PFMnCkpjFwVS+YJdZjRbe8K6BT0QBpLK20tm0IrKRM3iJE3wJVtB/1Ro430TnIkvpRj8/U8n9NXangMKpZDh+EGAEek+mmwzx28poFGLUiFm9PEVuwMtLiZRJ+QhaJPCNrQzlvvY5uqUeXnEpI3aW3DUS0VUvXWaC3Kt6h2zXZrUvavI69r+w8qSlQSvJegZFtAo3EiWf70IobPCqU57arxo4iqVNzT/l8hL29dS7JaTY8SOqoZO3vh4/A1CKe9kUadtJ1VNvbF328Ejo6sp4qmp2KwJgUwcgX4o+1RxWR+h1q+ZmRsq+f6bUye+0gYF5oNHH1boUlJbmIEtouCIRXTHKycJUk9aWMqHRBfjvPMdhIFiiPNTgXTH0IEntpEcXMKOFKCUS9HP6nKZZCU3CVtzx1O0WYWl2vEADnLwNqZX/RnE4DIh70=
